CREATE TABLE calendar(
           Dates date);

		   SET DATESTYLE = 'DMY';

		

CREATE TABLE customer(CustomerKey varchar(20),
		              Prefix	varchar(20),
					  FirstName	varchar(20),
					  LastName	varchar(20),
					  BirthDate	date,
					  MaritalStatus	varchar(20),
					  Gender	varchar(20),
					  EmailAddress	varchar(200),
					  AnnualIncome	int,
					  TotalChildren	int,
					  EducationLevel varchar(20),	
					  Occupation	varchar(50),
					  HomeOwner varchar(20));

CREATE TABLE prodcat(ProductCategoryKey varchar(20), CategoryName varchar(20))

					 
CREATE TABLE prodsubcat(ProductSubcategoryKey varchar(20),
	                    SubcategoryName varchar(20),
	                    ProductCategoryKey varchar(20) );

CREATE TABLE productlookup(ProductKey	varchar(20),
                     ProductSubcategoryKey varchar(20),
                     ProductSKU	varchar(200),
					 ProductName varchar(200),
					 ModelName	varchar(200),
					 ProductDescription	varchar(500),
					 ProductColor varchar(200),	
					 ProductSize varchar(200),	
					 ProductStyle varchar(200),	
					 ProductCost	numeric,
					 ProductPrice numeric);

CREATE TABLE returns(ReturnDate	date,
                     TerritoryKey int,
					 ProductKey varchar (20),
					 ReturnQuantity int );


CREATE TABLE territory(SalesTerritoryKey int,
                       Region varchar (20),
					   Country	 varchar (20),
					   Continent varchar (20));


CREATE TABLE sales(OrderDate date,
                   StockDate date,	
				   OrderNumber	varchar (20),
				   ProductKey	varchar (20),
				   CustomerKey	varchar (20),
				   TerritoryKey	int,
				   OrderLineItem int,	
				   OrderQuantity int);


-- Viewing the tables--
SELECT *
FROM calendar;

SELECT *
FROM customer; --c key


SELECT *
FROM prodcat; --pc key--

SELECT *
FROM prodsubcat; -- psc key--

SELECT *
FROM productlookup; -- p key, psc-key--

SELECT *
FROM returns; - --p key, t key--

SELECT *
FROM sales; -- c key, p key, t key --

SELECT * FROM territory -- t.key

-- ANSWERING BUSINESS QUESTIONS--

--Instructions: Write queries to answer the following questions: --


--1. Retrieve the customers who have placed orders with a total amount greater than $10000. --

SELECT c.customerkey,
        CONCAT_WS(' ', c.Prefix, c.FirstName, c.LastName) AS CustomerName,
    ROUND(SUM(s.OrderQuantity * p.ProductPrice),2) AS TotalAmount
FROM sales s
JOIN productlookup p 
    ON s.ProductKey = p.ProductKey
JOIN customer c
    ON s.CustomerKey = c.CustomerKey
GROUP BY  c.customerkey,c.Prefix, c.FirstName, c.LastName
HAVING ROUND(SUM(s.OrderQuantity * p.ProductPrice),2) > 10000
ORDER BY TotalAmount DESC;

SELECT * FROM quest_1
		
--2. Retrieve the total revenue and total orders generated by each product category --


WITH category_sales AS ( SELECT
      pc.CategoryName,
        ROUND((s.OrderQuantity * p.ProductPrice),2) AS Revenue,
        s.OrderNumber
    FROM sales s
    JOIN productlookup p
        ON s.ProductKey = p.ProductKey
    JOIN prodsubcat psc
        ON p.ProductSubcategoryKey = psc.ProductSubcategoryKey
    JOIN prodcat pc
      
        ON psc.ProductCategoryKey = pc.ProductCategoryKey
)
SELECT DISTINCT
    CategoryName,
    SUM(Revenue) OVER (PARTITION BY CategoryName) AS TotalRevenue,
    COUNT(OrderNumber) OVER (PARTITION BY CategoryName) AS TotalOrders
FROM category_sales
ORDER BY TotalRevenue DESC;

SELECT * FROM quest_2

/*3. Retrieve the names of products and their categories for products with a selling price greater
than the average selling price of all products. - SQ --*/

SELECT
    p.ProductName,
    pc.CategoryName,
    p.ProductPrice
FROM productlookup p
JOIN prodsubcat psc
    ON p.ProductSubcategoryKey = psc.ProductSubcategoryKey
JOIN prodcat pc
    ON psc.ProductCategoryKey = pc.ProductCategoryKey
WHERE p.ProductPrice >  (SELECT ROUND(AVG(ProductPrice),2)  
	                      FROM productlookup);

	SELECT * FROM quest_3					  


	

-- 4a. How many customers have placed orders in “Canada”? List the customer names SQ --
 CREATE VIEW quest_4a AS
SELECT COUNT(DISTINCT c.CustomerKey) AS num_customers
FROM customer c
WHERE c.CustomerKey IN (
    SELECT s.CustomerKey
    FROM sales s
    WHERE s.TerritoryKey IN (
        SELECT t.SalesTerritoryKey
        FROM territory t
        WHERE t.Country = 'Canada'));

	SELECT * FROM quest_4a					  

----4b--List the customer names--

SELECT CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName
FROM customer c
WHERE c.CustomerKey IN (
    SELECT s.CustomerKey
    FROM sales s
    WHERE s.TerritoryKey IN (
        SELECT t.SalesTerritoryKey
        FROM territory t
        WHERE t.Country = 'Canada'
    )
)
ORDER BY CustomerName;

SELECT * FROM quest_4b	

 



--5. Find the 10 products that have been returned the most. How much money was generated by these products? -SB -- 

SELECT
    p.ProductName,
    r.total_returned,
    (SELECT SUM(s.OrderQuantity * pl.ProductPrice)
     FROM sales s
     JOIN productlookup pl ON s.ProductKey = pl.ProductKey
     WHERE s.ProductKey = r.ProductKey
    ) AS total_revenue
FROM (
    SELECT ProductKey, SUM(ReturnQuantity) AS total_returned
    FROM returns
    GROUP BY ProductKey
    ORDER BY total_returned DESC
    LIMIT 10
) AS r
JOIN productlookup p ON r.ProductKey = p.ProductKey
ORDER BY r.total_returned DESC;

SELECT * FROM quest_5a	

--5b--
WITH top10_returns AS (
    SELECT
        r.ProductKey,
        p.ProductName,
        SUM(r.ReturnQuantity) AS total_returned
    FROM returns r
    JOIN productlookup p ON r.ProductKey = p.ProductKey
    GROUP BY r.ProductKey, p.ProductName
    ORDER BY total_returned DESC
    LIMIT 10
)
SELECT
    tr.ProductKey,
    tr.ProductName,
    tr.total_returned,
    SUM(s.OrderQuantity * pl.ProductPrice) AS total_revenue
FROM top10_returns tr
JOIN sales s ON tr.ProductKey = s.ProductKey
JOIN productlookup pl ON s.ProductKey = pl.ProductKey
GROUP BY tr.ProductKey, tr.ProductName, tr.total_returned
ORDER BY tr.total_returned DESC;

SELECT * FROM quest_5a	

	
--6. Get a list of customers who have placed orders in more than one territory. --

SELECT
    customerkey,
    COUNT(DISTINCT territorykey) AS num_territories
FROM sales 
GROUP BY customerkey
HAVING COUNT(DISTINCT territorykey) > 1;


SELECT
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    COUNT(DISTINCT s.TerritoryKey) AS num_territories
FROM customer c
JOIN sales s ON c.CustomerKey = s.CustomerKey
GROUP BY c.CustomerKey, c.FirstName, c.LastName
HAVING COUNT(DISTINCT s.TerritoryKey) > 1
ORDER BY num_territories DESC, CustomerName;



--7. Retrieve the product names and their corresponding sub-categories for products that have been ordered at least 10 times. --
 CREATE VIEW quest_7 AS    
SELECT
    p.ProductName,
    ps.SubcategoryName
FROM productlookup p
JOIN prodsubcat ps ON p.ProductSubcategoryKey = ps.ProductSubcategoryKey
JOIN sales s ON p.ProductKey = s.ProductKey
GROUP BY p.ProductName, ps.SubcategoryName
HAVING SUM(s.OrderQuantity) >= 10
ORDER BY p.ProductName;

SELECT * FROM quest_7	



--8a. List the customer names who have placed orders after 2021. What is the distribution of their occupation? --
 CREATE VIEW quest_8a AS
SELECT
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
  
    COUNT(*) AS num_orders
FROM customer c
JOIN sales s ON c.CustomerKey = s.CustomerKey
WHERE s.OrderDate > '2021-12-31'
GROUP BY c.CustomerKey, c.FirstName, c.LastName
ORDER BY CustomerName;

SELECT * FROM quest_8a
--8b What is the distribution of their occupation? --
 CREATE VIEW quest_8b AS
SELECT
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    c.Occupation
FROM customer c
JOIN sales s ON c.CustomerKey = s.CustomerKey
WHERE s.OrderDate > '2021-12-31'
GROUP BY c.CustomerKey, c.FirstName, c.LastName, c.Occupation
ORDER BY c.Occupation, CustomerName;


SELECT * FROM quest_8b


--9. Get a list of products and their corresponding order quantities for products that have been ordered at least once. --
 CREATE VIEW quest_9 AS
SELECT
    p.ProductName,
    SUM(s.OrderQuantity) AS total_ordered
FROM productlookup p
JOIN sales s ON p.ProductKey = s.ProductKey
GROUP BY p.ProductName
HAVING SUM(s.OrderQuantity) > 0
ORDER BY total_ordered DESC;

SELECT * FROM quest_9

--10.Retrieve the product names that start with the letter "C" or “H” and are from the "Clothing" category. --
 CREATE VIEW quest_10 AS
SELECT
    p.ProductName
FROM productlookup p
JOIN prodsubcat ps ON p.ProductSubcategoryKey = ps.ProductSubcategoryKey
JOIN prodcat pc ON ps.ProductCategoryKey = pc.ProductCategoryKey
WHERE pc.CategoryName = 'Clothing'
  AND (p.ProductName LIKE 'C%' OR p.ProductName LIKE 'H%')
ORDER BY p.ProductName;

SELECT * FROM quest_10


11.Retrieve the product names that have been ordered in the ‘United States’ or "Australia". 
 CREATE VIEW quest_11 AS
SELECT DISTINCT p.ProductName
FROM productlookup p
JOIN sales s ON p.ProductKey = s.ProductKey
JOIN territory t ON s.TerritoryKey = t.SalesTerritoryKey
WHERE t.Country IN ('United States', 'Australia')
ORDER BY p.ProductName;

SELECT * FROM quest_11


--12.Find the customer names who have placed orders with a total amount greater than the average total amount of orders. – SQ --
 CREATE VIEW quest_12 AS
SELECT CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName
FROM customer c
JOIN sales s ON c.CustomerKey = s.CustomerKey
JOIN productlookup p ON s.ProductKey = p.ProductKey
GROUP BY c.CustomerKey, c.FirstName, c.LastName
HAVING SUM(s.OrderQuantity * p.ProductPrice) > (
    SELECT AVG(total_amount) 
    FROM (
        SELECT SUM(s2.OrderQuantity * p2.ProductPrice) AS total_amount
        FROM sales s2
        JOIN productlookup p2 ON s2.ProductKey = p2.ProductKey
        GROUP BY s2.CustomerKey
    ) AS customer_totals
)
ORDER BY CustomerName;

SELECT * FROM quest_12

--13.Retrieve the top 5 customers who have placed the highest number of orders, along with their order counts. --
 CREATE VIEW quest_13 AS
SELECT
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    COUNT(s.OrderNumber) AS order_count
FROM customer c
JOIN sales s ON c.CustomerKey = s.CustomerKey
GROUP BY c.CustomerKey, c.FirstName, c.LastName
ORDER BY order_count DESC
LIMIT 5;

SELECT * FROM quest_13


--14.List the customers who have placed orders within the last 6 months (consider the last date in the data) --
 CREATE VIEW quest_14 AS
SELECT DISTINCT CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName
FROM customer c
JOIN sales s ON c.CustomerKey = s.CustomerKey
WHERE s.OrderDate >= '2021-12-31'
ORDER BY CustomerName;

SELECT * FROM quest_14

--15. We want to reach out to our best customers in 2022. Can you get emails of Top 50 customers based on revenue? --
  CREATE VIEW quest_15 AS
SELECT
    c.EmailAddress,
    SUM(s.OrderQuantity * p.ProductPrice) AS total_revenue
FROM customer c
JOIN sales s ON c.CustomerKey = s.CustomerKey
JOIN productlookup p ON s.ProductKey = p.ProductKey
WHERE s.OrderDate BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY c.CustomerKey, c.EmailAddress
ORDER BY total_revenue DESC
LIMIT 50;

SELECT * FROM  quest_15
                                             